### PR TITLE
JupyterLab 2

### PR DESCRIPTION
**Pull request by martinRenou**
jlab

### CODE REVIEW

**Comment by martinRenou** [comment]
Remaining: 
- [ ] : Column type change
- [ ] : Column name change
- [ ] : Filters change
- [ ] : Alignment change
- [ ] : Get rid of the SelectionManager (maybe in a separate PR?)
- [ ] : Columns/rows not resizable individually

**Comment by EfimovVladimir** [comment]
The empty space appears near edge of table.
expected result:
image
actual result:
image

**Comment by EfimovVladimir** [comment]
running cell by doubleClick doesn't work
expected result:
image
actual result:
image

**Comment by EfimovVladimir** [comment]
The logic was changed for `setColumnOrder()` function
expected result: it display only 5 columns in order
image
actual result: it display 5 columns in order + other columns
image

**Comment by EfimovVladimir** [comment]
The image of scrollbar arrows was changed
expected result:
image
actual result:
image

**Comment by martinRenou** [comment]
Thanks a lot for the review @EfimovVladimir !

**Comment by martinRenou** [comment]
@EfimovVladimir I fixed the sizing issue and the sorting issue. Concerning the double click issue you mentioned, I think you just forgot to run the second cell, I see it working on my side.

The e2e testing is not passing, mostly due to an extra line of pixels that is not visible with the eye, I guess we can ignore those?

**Comment by EfimovVladimir** [comment]
@martinRenou yep, we can ignore e2e in our case

**Comment by EfimovVladimir** [comment]
The image of submenu arrows was changed
expected result:
image

actual result:
image

**Comment by EfimovVladimir** [comment]
The logic of single click on column header was changed.
Expected result when we do single click on column header : 
1. it doesn't scroll page.
2. it doesn't activate header for `drag and drop` action

Peek 2021-01-13 00-51

Actual result when we do single click on column header : 
1. it scrolls page.
2. it activates header for `drag and drop` action.
 
Peek 2021-01-13 00-50

The way of sorting table by single click or double click is open to discuss.

**Comment by martinRenou** [comment]
Thanks.

The submenu icon might be due to font-awesome changes, I'll investigate.

Concerning events, the grid is no relying on the Lumino datagrid for most mouse events like clicks/scroll/drag and drop. Do you see those changes as a blocker to merge this PR? If you do, then we should revert my changes on the mouse events and not use the Lumino datagrid mouse events. IMO it is better to rely on their logic, so that there is no duplication of effort there.

**Pull request merged**
