### PR TITLE
Add benchmark for large table

### PR DESCRIPTION
**Pull request by fcollonval**
Preliminary work for addressing https://github.com/twosigma/beakerx_tabledisplay/issues/68

### CODE REVIEW

**Comment by fcollonval** [comment]
Small note: the new workflow won't be tested before being merged (as it needs to be on the default branch).

**Comment by martinRenou** [comment]
IIRC there is already end-to-end testing: See https://github.com/twosigma/beakerx_tabledisplay/blob/master/.github/workflows/python-package.yml#L135 and https://github.com/twosigma/beakerx_tests/blob/master/autotests/ci_tests.py

Would it be fine to replace those tests with Galata tests? @afshin

I guess we can also live with both `beakerx_tests` and `galata` for some time, too much testing is not so bad.

**Comment by afshin** [comment]
I think benchmark/performance tests are the main thing that would help. The existing `e2e` tests are about functionality primarily, I think.

cc: @ildipo @diegoalbertotorres

**Comment by fcollonval** [comment]
> Would it be fine to replace those tests with Galata tests?

I don't think this is worth the required investment (the existing tool is using another browser driver - aka selenium; so transition may not be easy). As @afshin pointed out, the existing e2e tests are targeting functionality. This introduces measurement with no target on functional testing; so no redundancy.

**Pull request merged**
